name: transport_management
description: Intelligent Public Transport Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true